[project]
name = "fastapi-base"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "more-itertools>=10.7.0",
    "sqlmodel>=0.0.24",
    "starlette-admin>=0.15.1",
    "tqdm>=4.67.1",
]
